definitions:
  model.CommentDTO:
    properties:
      content:
        type: string
      id:
        type: string
      userId:
        type: integer
      userName:
        type: string
    type: object
info:
  contact: {}
paths:
  /comments:
    post:
      consumes:
      - application/json
      description: Create a comment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CommentDTO'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a comment
      tags:
      - comments
  /comments/{id}:
    get:
      consumes:
      - application/json
      description: Get a comment by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CommentDTO'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get a comment by id
      tags:
      - comments
swagger: "2.0"
